[package]
name = "loom-engine-tool-macro"
version = "0.1.0"
edition = "2024"
license-file = "../LICENSE"

[lib]
proc-macro = true
name = "loom_engine_tool_macro"
path = "src/lib.rs"

[dependencies]
default = "0.1.2"
linkme = "0.3.35"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full", "parsing"] }

[dev-dependencies]
anyhow.workspace = true
loom-engine = { path = "../loom-engine" }
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
